services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=4001
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    container_name: pol_designer_backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5180:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    container_name: pol_designer_frontend