services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=4001
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:4001/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    container_name: pol_designer_backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    container_name: pol_designer_frontend